@startuml
!include ../style.puml
skinparam ClassBorderColor MODEL_COLOR
skinparam ClassBackgroundColor MODEL_COLOR_T1
skinparam ArrowColor MODEL_COLOR

title After command "deletealias ls"

object "<u>aliasList:AliasList</u>" as list {
}

object "<u>ap:Alias</u>" as addproduct {
}

object "<u>lp:Alias</u>" as listproduct {
}

list --> addproduct
list --> listproduct

@enduml
