@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "Inventory Storage" #F4F6F6{
Class "<<interface>>\nInventoryStorage" as InventoryStorage
Class JsonInventoryStorage
Class JsonSerializableInventory
Class JsonAdaptedProduct
}

package "Alias Storage" #F4F6F6{
Class "<<interface>>\nAliasStorage" as AliasStorage
Class JsonAliasStorage
Class JsonSerializableAlias
class JsonAdaptedAlias
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -down-> "1" UserPrefsStorage
StorageManager -down-> "1" AddressBookStorage
StorageManager -down-> "1" InventoryStorage
StorageManager -down-> "1" AliasStorage

Storage -down-|> UserPrefsStorage
Storage -down-|> AddressBookStorage
Storage -down-|> InventoryStorage
Storage -down-|> AliasStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage

JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

JsonInventoryStorage .up.|> InventoryStorage
JsonInventoryStorage ..> JsonSerializableInventory
JsonSerializableInventory --> "*" JsonAdaptedProduct

JsonAliasStorage .up.|> AliasStorage
JsonAliasStorage ..> JsonSerializableAlias
JsonSerializableAlias --> "*" JsonAdaptedAlias

@enduml
