@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

box "Logic" LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ListCommand" as ListCommand LOGIC_COLOR
end box

box "Model" MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":Aliases" as Aliases MODEL_COLOR
participant ":AliasList" as AliasList MODEL_COLOR
end box

[-> LogicManager : execute("ls")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("ls", pendingConfirmation, model)
activate AddressBookParser

note right of AddressBookParser
    Extracts command word "ls"
    from user input
end note

AddressBookParser -> ModelManager : findAlias("ls")
activate ModelManager

ModelManager -> Aliases : findAlias("ls")
activate Aliases

Aliases -> AliasList : findAlias("ls")
activate AliasList
AliasList --> Aliases : alias
deactivate AliasList

Aliases --> ModelManager : alias
deactivate Aliases


ModelManager --> AddressBookParser : alias
deactivate ModelManager

note right of AddressBookParser
    alias.getOriginalCommand()
    returns "list"
end note

AddressBookParser --> LogicManager : listCommand
create ListCommand
AddressBookParser -> ListCommand : new ListCommand()
deactivate AddressBookParser

LogicManager -> ListCommand : execute(model)
activate ListCommand
ListCommand --> LogicManager : commandResult
deactivate ListCommand

[<-- LogicManager : commandResult
deactivate LogicManager

@enduml
