@startuml
!include ../style.puml
skinparam ClassBorderColor MODEL_COLOR
skinparam ClassBackgroundColor MODEL_COLOR_T1
skinparam ArrowColor MODEL_COLOR

title After adding alias ls

object "aliasList: AliasList" as list {
}

object "ap : Alias" as addproduct {
}

object "lp : Alias" as listproduct {
}

object "ls : Alias" as ls {
}

list --> addproduct
list --> listproduct
list --> ls
@enduml
