@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":ModelManager" as Model MODEL_COLOR
participant ":VersionedVendorVault" as VersionedVendorVault MODEL_COLOR
participant "currentState:VendorVault" as VendorVault MODEL_COLOR
end box

[-> Model : undoVendorVault()
activate Model

Model -> VersionedVendorVault : undo(currentState)
activate VersionedVendorVault

VersionedVendorVault -> VendorVault : resetData(previousState)
activate VendorVault
VendorVault --> VersionedVendorVault
deactivate VendorVault

VersionedVendorVault --> Model : actionSummary
deactivate VersionedVendorVault

[<-- Model : actionSummary
deactivate Model

@enduml
